import { getPool } from "./pool";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface EmailHistoryRow {
  id: string;
  message_id: string | null;
  recipient_email: string;
  email_type: string;
  sent_at: Date;
  status: "sent" | "failed";
  error_message: string | null;
}

export interface InsertEmailHistoryInput {
  /** Caller-supplied idempotency UUID. When provided it becomes the row id.
   *  Omit to let Postgres auto-generate a uuidv7(). */
  id?: string;
  /** SMTP message-id (on success) or a synthetic UUID (on failure). */
  message_id?: string;
  /** First recipient address — used for audit/search. */
  recipient_email: string;
  /** Template type key (e.g. "welcome", "order_confirmation"). */
  email_type: string;
  status: "sent" | "failed";
  error_message?: string;
}

// ---------------------------------------------------------------------------
// Queries
// ---------------------------------------------------------------------------

/**
 * Look up an email_history row by its primary key (= the caller's idempotency key).
 * Returns `null` when no matching row exists.
 */
export async function findById(id: string): Promise<EmailHistoryRow | null> {
  const client = await getPool().connect();
  try {
    const result = await client.query<EmailHistoryRow>(
      "SELECT * FROM rental.email_history WHERE id = $1",
      [id]
    );
    return result.rows[0] ?? null;
  } finally {
    client.release();
  }
}

/**
 * Insert one row into email_history.
 *
 * When `input.id` is provided it is used as the explicit row id (idempotency
 * key). The primary-key constraint de-duplicates concurrent inserts:
 * ON CONFLICT (id) DO NOTHING means a second identical request simply
 * produces no row change, preserving the first outcome.
 *
 * When `input.id` is omitted the row id is auto-generated by uuidv7().
 */
export async function insertEmailHistory(
  input: InsertEmailHistoryInput
): Promise<void> {
  const client = await getPool().connect();
  try {
    await client.query(
      `INSERT INTO rental.email_history
         (id, message_id, recipient_email, email_type, status, error_message)
       VALUES
         (COALESCE($1::uuid, uuidv7()), $2, $3, $4, $5, $6)
       ON CONFLICT (id) DO NOTHING`,
      [
        input.id ?? null,
        input.message_id ?? null,
        input.recipient_email,
        input.email_type,
        input.status,
        input.error_message ?? null,
      ]
    );
  } finally {
    client.release();
  }
}
